app/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.home.urls', namespace='home')),
    path('security/', include('core.security.urls', namespace='security')), 
    path('dashboard/', include('core.dashboard.urls', namespace='dashboard')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/dashboard/urls.py
from django.urls import path
from core.dashboard.views import home, category, units, product, point

app_name = "dashboard"

urlpatterns = [
    #DASHBOARD
    path('',home.DashboardView.as_view(),name="home"),
    path('ver-productos/', home.ProductView.as_view(), name='product_view'),

    #CATEGORY
    path('categories/', category.CategoryListView.as_view(), name="category_list"),
    path('categories/create/', category.CategoryCreateView.as_view(), name="category_create"),
    path('categories/<int:pk>/update/', category.CategoryUpdateView.as_view(), name="category_update"),
    path('categories/<int:pk>/delete/', category.CategoryDeleteView.as_view(), name="category_delete"),

    #UNITS
    path('units/', units.UnitsListView.as_view(), name='unit_list'),
    path('units/create/', units.UnitsCreateView.as_view(), name='unit_create'),
    path('units/<int:pk>/edit/', units.UnitsUpdateView.as_view(), name='unit_edit'),
    path('units/<int:pk>/delete/', units.UnitsDeleteView.as_view(), name='unit_delete'),

    #PRODUCTS
    path('products/', product.ProductListView.as_view(), name='product_list'),
    path('products/create/', product.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/edit/', product.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', product.ProductDeleteView.as_view(), name='product_delete'),
    path('products/<int:pk>/toggle-status/', product.ProductToggleStatusView.as_view(), name='product_toggle_status'),
    path('product/request/<int:product_id>/', home.ProductRequestCreateView.as_view(), name='request_product'),


    #REQUEST PRODUCT
    path('product-requests/', point.ProductRequestListView.as_view(), name='product_requests_list'),
    path('product-requests/action/<int:pk>/', point.ProductRequestActionView.as_view(), name='product_request_action'),

    #HISTORY POINT
    path('point-history/', point.PointHistoryListView.as_view(), name='point_history'),

    #REWARS
    path('rewards/', home.RewardListView.as_view(), name='rewards_list'),
    path('rewards/create/', home.RewardCreateView.as_view(), name='reward_create'),
    path('rewards/<int:pk>/edit/', home.RewardUpdateView.as_view(), name='reward_edit'),
    path('rewards/<int:pk>/delete/', home.RewardDeleteView.as_view(), name='reward_delete'),

    path("redeem/<int:pk>/confirm/", home.RedeemRewardConfirmationView.as_view(), name="redeem_confirm"),
    path("redeem/<int:pk>/", home.RedeemRewardView.as_view(), name="redeem"),
]

app/core/dashboard/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
import os


def validate_image_extension(value):
    ext = os.path.splitext(value.name)[1].lower()
    if ext not in ['.jpg', '.jpeg']:
        raise ValidationError("Solo se permiten imágenes con formato .jpg o .jpeg.")


class Units(models.Model):
    name = models.CharField(max_length=50, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_units"
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="updated_units"
    )
    
    class Meta:
        verbose_name = 'Unidad'
        verbose_name_plural = 'Unidades'
    
    def __str__(self):
        return f"{self.name} ({self.abbreviation})"
    

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_categories"
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="updated_categories"
    )
    
    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
    
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='products/', validators=[validate_image_extension])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    units = models.ForeignKey(Units, on_delete=models.CASCADE, related_name="products")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_products"
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="updated_products"
    )

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
    
    def __str__(self):
        return self.name

class Points(models.Model):
    ACTION_CHOICES = [
        ('TASK_COMPLETED', 'Tarea Completada'),
        ('PRODUCT_REQUEST', 'Solicitud de Producto'),
        ('PURCHASE', 'Compra Realizada'),
        ('PENALTY', 'Penalización'),
    ]

    number = models.PositiveIntegerField()  # Puntos otorgados (pueden ser negativos también si es una penalización)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="points")
    action_type = models.CharField(max_length=50, choices=ACTION_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_points"
    )

    class Meta:
        verbose_name = 'Punto'
        verbose_name_plural = 'Puntos'

    def __str__(self):
        return f"{self.number} puntos para {self.user} por {self.get_action_type_display()}"


class PointHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="point_history")
    points = models.PositiveIntegerField()
    action = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_point_histories"
    )

    class Meta:
        verbose_name = 'Historial de Puntos'
        verbose_name_plural = 'Historial de Puntos'

    def __str__(self):
        return f"{self.points} puntos - {self.action}"


class ProductRequest(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pendiente'),
        ('APPROVED', 'Aprobada'),
        ('DENIED', 'Denegada'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name="product_requests"
    )
    product = models.ForeignKey(
        Product, 
        on_delete=models.CASCADE, 
        related_name="requests"
    )
    status = models.CharField(
        max_length=10, 
        choices=STATUS_CHOICES, 
        default='PENDING'
    )
    points_assigned = models.PositiveIntegerField(default=0, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name="reviewed_requests"
    )

    class Meta:
        verbose_name = 'Solicitud de Producto'
        verbose_name_plural = 'Solicitudes de Producto'

    def __str__(self):
        return f"Solicitud de {self.user} para {self.product} - {self.get_status_display()}"

    def approve(self, admin_user, points):
        if points < 0:
            raise ValidationError("Los puntos no pueden ser negativos.")
        
        # Verificar si ya existen puntos asignados para la solicitud
        existing_points = Points.objects.filter(user=self.user, action_type='PRODUCT_REQUEST').first()
        if existing_points:
            # Si ya existe un registro de puntos, actualízalo en lugar de crear uno nuevo
            existing_points.number += points
            existing_points.save()
        else:
            # Si no existe, crea uno nuevo
            Points.objects.create(
                user=self.user,
                number=points,
                action_type='PRODUCT_REQUEST',
                created_by=admin_user
            )

        self.status = 'APPROVED'
        self.reviewed_by = admin_user
        self.points_assigned = points
        self.save()

        # Registrar el historial de puntos
        PointHistory.objects.create(
            user=self.user,
            points=points,
            action=f"Producto gestionado: {self.product.name}",
            created_by=admin_user
        )

    def deny(self, admin_user):
        self.status = 'DENIED'
        self.reviewed_by = admin_user
        self.save()

class Reward(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    points_required = models.PositiveIntegerField()
    image = models.ImageField(upload_to='rewards/')
    
    def __str__(self):
        return self.name

app/core/dashboard/views.py
from django.shortcuts import render

# Create your views here.

app/core/dashboard/views/category.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from core.dashboard.models import Category
from core.dashboard.forms.categoryform import CategoryForm

class CategoryListView(ListView):
    model = Category
    template_name = 'core/dashboard/category/category_list.html'
    context_object_name = 'categories'
    
    def get_queryset(self):
        queryset = Category.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(name__icontains=query)
        return queryset

class CategoryCreateView(CreateView):
    model = Category
    template_name = 'core/dashboard/category/category_form.html'
    form_class = CategoryForm
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)
    
    success_url = reverse_lazy('dashboard:category_list')


class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'core/dashboard/category/category_form.html'
    form_class = CategoryForm

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)
    
    success_url = reverse_lazy('dashboard:category_list')


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'core/dashboard/category/category_delete.html'
    
    success_url = reverse_lazy('dashboard:category_list')

app/core/dashboard/views/home.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, View, ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseForbidden
from core.dashboard.models import Product, ProductRequest, Reward, PointHistory, Points

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'core/dashboard/home.html'
    login_url = '/security/auth/login'

class RewardListView(ListView):
    model = Reward
    template_name = 'core/dashboard/rewards/rewards.html'
    context_object_name = 'rewards'

    def get_queryset(self):
        return Reward.objects.all()
    
class RewardCreateView(CreateView):
    model = Reward
    template_name = 'core/dashboard/rewards/reward_form.html'
    fields = ['name', 'description', 'points_required', 'image']
    success_url = reverse_lazy('dashboard:rewards_list')

    def form_valid(self, form):
        return super().form_valid(form)
    
class RewardUpdateView(UpdateView):
    model = Reward
    template_name = 'core/dashboard/rewards/reward_form.html'
    fields = ['name', 'description', 'points_required', 'image']
    context_object_name = 'reward'
    success_url = reverse_lazy('dashboard:rewards_list')

    def form_valid(self, form):
        return super().form_valid(form)
    
class RewardDeleteView(DeleteView):
    model = Reward
    template_name = 'core/dashboard/rewards/reward_delete.html'
    context_object_name = 'reward'
    success_url = reverse_lazy('dashboard:rewards_list') 


class RedeemRewardConfirmationView(LoginRequiredMixin, TemplateView):
    template_name = "core/dashboard/rewards/redeem_confirmation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reward_id = self.kwargs.get("pk")
        reward = get_object_or_404(Reward, id=reward_id)
        context["reward"] = reward
        return context


class RedeemRewardView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        reward_id = kwargs.get("pk")
        reward = get_object_or_404(Reward, id=reward_id)
        user = request.user

        # Calcular los puntos del usuario
        total_points = sum(point.number for point in user.points.all())

        if total_points < reward.points_required:
            messages.error(request, "No tienes suficientes puntos para canjear este premio.")
            return redirect(reverse_lazy("rewards:reward_list"))

        # Registrar en el historial de puntos
        PointHistory.objects.create(
            user=user,
            points=reward.points_required,
            action=f"Canjeado: {reward.name}",
            created_by=user,
        )

        messages.success(request, f"Has canjeado el premio: {reward.name}.")
        return redirect(reverse_lazy("dashboard:rewards_list"))

class ProductView(LoginRequiredMixin, TemplateView):
    template_name = 'core/dashboard/product.html'
    login_url = '/security/auth/login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context
    
class ProductRequestCreateView(View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        return render(request, 'core/request/request.html', {'product': product})

    def post(self, request, product_id):
        if not request.user.is_authenticated:
            return HttpResponseForbidden("No tienes permiso para realizar esta acción.")

        product = get_object_or_404(Product, id=product_id)

        ProductRequest.objects.create(
            user=request.user,
            product=product,
            status='Pendiente',
        )

        messages.success(request, f'Solicitud para el producto {product.name} creada correctamente.')
        return redirect('dashboard:product_view')

app/core/dashboard/views/units.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from core.dashboard.models import Units
from core.dashboard.forms.unitsform import UnitsForm
from django.contrib.auth.mixins import LoginRequiredMixin

class UnitsListView(LoginRequiredMixin, ListView):
    model = Units
    template_name = 'core/dashboard/units/unit_list.html'
    context_object_name = 'units'
    
    def get_queryset(self):
        queryset = Units.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(description__icontains=query)
        return queryset

class UnitsCreateView(LoginRequiredMixin, CreateView):
    model = Units
    template_name = 'core/dashboard/units/unit_form.html'
    form_class = UnitsForm
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)
    
    success_url = reverse_lazy('dashboard:unit_list')

class UnitsUpdateView(LoginRequiredMixin, UpdateView):
    model = Units
    template_name = 'core/dashboard/units/unit_form.html'
    form_class = UnitsForm

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)
    
    success_url = reverse_lazy('dashboard:unit_list')

class UnitsDeleteView(LoginRequiredMixin, DeleteView):
    model = Units
    template_name = 'core/dashboard/units/unit_delete.html'
    
    success_url = reverse_lazy('dashboard:unit_list')

app/templates/core/dashboard/products/product_delete.html
{% extends 'components/base_dash.html' %}

{% block title %}Eliminar Producto{% endblock %}

{% block content %}
    <div class="container mx-auto p-6">
        <h2 class="text-2xl font-bold mb-6">¿Estás seguro de que deseas eliminar este producto?</h2>

        <div class="bg-gray-800 p-6 rounded-lg shadow-md">
            <h3 class="text-lg text-white mb-4">{{ object.description }}</h3>
            <p class="text-gray-300 mb-6">Esta acción no puede deshacerse.</p>

            <form method="post">
                {% csrf_token %}
                <div class="flex justify-end space-x-4">
                    <a href="{% url 'dashboard:product_list' %}" class="bg-gray-500 text-white px-6 py-2 rounded-md hover:bg-gray-600">
                        Cancelar
                    </a>

                    <button type="submit" class="bg-red-600 text-white px-6 py-2 rounded-md hover:bg-red-700">
                        Eliminar
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/core/dashboard/products/product_form.html
{% extends 'components/base_dash.html' %}

{% block title %}Crear/Editar Producto{% endblock %}

{% block content %}
    <div class="container mx-auto p-6">
        <h2 class="text-2xl font-bold mb-6">
            {% if form.instance.pk %}
                Editar Producto
            {% else %}
                Crear Nuevo Producto
            {% endif %}
        </h2>

        <form method="post" enctype="multipart/form-data" class="bg-gray-800 p-6 rounded-lg shadow-md">
            {% csrf_token %}

            <div class="mb-4">
                <label for="id_name" class="block text-white font-medium mb-2">Nombre del producto</label>
                <input type="text" name="name" id="id_name" value="{{ form.name.value|default:'' }}" class="form-input px-4 py-2 w-full rounded-md border border-gray-600 bg-gray-700 text-white placeholder-gray-400 focus:ring-2 focus:ring-blue-500" placeholder="Nombre del producto" required>
            </div>

            <div class="mb-4">
                <label for="id_description" class="block text-white font-medium mb-2">Descripción del producto</label>
                <textarea name="description" id="id_description" class="form-input px-4 py-2 w-full rounded-md border border-gray-600 bg-gray-700 text-white placeholder-gray-400 focus:ring-2 focus:ring-blue-500" placeholder="Descripción del producto" required>{{ form.description.value|default:'' }}</textarea>
            </div>

            <div class="mb-4">
                <label for="id_image" class="block text-white font-medium mb-2">Imagen del producto</label>
                <input type="file" name="image" id="id_image" class="form-input px-4 py-2 w-full rounded-md border border-gray-600 bg-gray-700 text-white placeholder-gray-400 focus:ring-2 focus:ring-blue-500">
                {% if form.instance.pk and form.instance.image %}
                    <div class="mt-4">
                        <img src="{{ form.instance.image.url }}" alt="Imagen actual" class="w-32 h-32 object-cover">
                    </div>
                {% endif %}
            </div>

            <div class="mb-4">
                <label for="id_units" class="block text-white font-medium mb-2">Unidad de medida</label>
                <select name="units" id="id_units" class="form-select px-4 py-2 w-full rounded-md border border-gray-600 bg-gray-700 text-white focus:ring-2 focus:ring-blue-500">
                    <option value="" disabled {% if not form.units.value %}selected{% endif %}>Seleccione la unidad de medida</option>
                    {% for unit in units %}
                        <option value="{{ unit.id }}" {% if unit.id == form.units.value %}selected{% endif %}>{{ unit.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-4">
                <label for="id_category" class="block text-white font-medium mb-2">Categoría</label>
                <select name="category" id="id_category" class="form-select px-4 py-2 w-full rounded-md border border-gray-600 bg-gray-700 text-white focus:ring-2 focus:ring-blue-500">
                    <option value="" disabled {% if not form.category.value %}selected{% endif %}>Seleccione la categoría</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if category.id == form.category.value %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-4">
                <label for="id_is_active" class="block text-white font-medium mb-2">Estado del producto</label>
                <input type="checkbox" name="is_active" id="id_is_active" {% if form.is_active.value %}checked{% endif %} class="form-checkbox text-blue-500" />
                <span class="text-white">Activo</span>
            </div>

            <div class="flex items-center justify-between">
                <a href="{% url 'dashboard:product_list' %}" class="bg-gray-500 text-white hover:bg-gray-600 py-2 px-4 rounded-md mr-4">
                    Volver a la lista de productos
                </a>

                <button type="submit" class="bg-blue-500 text-white px-6 py-2 rounded-md hover:bg-blue-600">
                    {% if form.instance.pk %}
                        Guardar cambios
                    {% else %}
                        Crear producto
                    {% endif %}
                </button>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/core/dashboard/products/product_list.html
{% extends 'components/base_dash.html' %}

{% block title %}Productos a Reciclar{% endblock %}

{% block content %}
    <div class="container mx-auto p-2">
        <h2 class="text-2xl font-bold mb-6">Productos a Reciclar</h2>

        <!-- Search Form -->
        <div class="mb-4">
            <form method="get" action="{% url 'dashboard:product_list' %}" class="flex items-center">
                <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Buscar productos..." class="form-input px-4 py-2 rounded-md w-full border border-gray-600">
                <button type="submit" class="ml-2 bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">
                    Buscar
                </button>
            </form>
        </div>

        <div class="mt-6 mb-6">
            <a href="{% url 'dashboard:product_create' %}" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">Crear nuevo producto</a>
        </div>

        <table class="min-w-full bg-gray-800 text-white rounded-md shadow-md">
            <thead>
                <tr>
                    <th class="py-3 px-6 text-left">Imagen</th>
                    <th class="py-3 px-6 text-left">Nombre</th>
                    <th class="py-3 px-6 text-left">Unidad</th>
                    <th class="py-3 px-6 text-left">Categoría</th>
                    <th class="py-3 px-6 text-left">Fecha de Creación</th>
                    <th class="py-3 px-6 text-left">Última Actualización</th>
                    <th class="py-3 px-6 text-left">Estado</th>
                    <th class="py-3 px-6 text-left">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr class="border-b border-gray-700">
                        <td class="py-3 px-6">
                            <img src="{{ product.image.url }}" alt="{{ product.description }}" class="w-16 h-16 object-cover">
                        </td>
                        <td class="py-3 px-6">{{ product.name }}</td>
                        <td class="py-3 px-6">{{ product.units.name }}</td>
                        <td class="py-3 px-6">{{ product.category.name }}</td>
                        <td class="py-3 px-6">{{ product.created_at }}</td>
                        <td class="py-3 px-6">{{ product.updated_at }}</td>
                        <td class="py-3 px-6">
                            {% if product.is_active %}
                                <span class="text-green-500">Activo</span>
                            {% else %}
                                <span class="text-red-500">Inactivo</span>
                            {% endif %}
                        </td>
                        <td class="py-3 px-6">
                            <div class="flex space-x-4">
                                <a href="{% url 'dashboard:product_update' product.id %}" class="text-yellow-400 hover:text-yellow-500 flex items-center">
                                    <i class="bx bx-edit-alt mr-2"></i>
                                </a>
                                <a href="{% url 'dashboard:product_delete' product.id %}" class="text-red-500 hover:text-red-600 flex items-center">
                                    <i class="bx bx-trash mr-2"></i> 
                                </a>
                                <a href="{% url 'dashboard:product_toggle_status' product.id %}" class="text-blue-500 hover:text-blue-600 flex items-center">
                                    <i class="bx bx-toggle mr-2"></i>
                                    {% if product.is_active %}
                                        Desactivar
                                    {% else %}
                                        Activar
                                    {% endif %}
                                </a>
                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="8" class="py-3 px-6 text-center">No hay productos disponibles</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}